import { Entity, PrimaryGeneratedColumn, Column } from 'typeorm';

@Entity({ name: 'relatorio' })
export class Relatorio {
  @PrimaryGeneratedColumn('uuid') id!: string;
  @Column({ type: 'varchar', length: 10, nullable: true }) Dia!: string | null;
  @Column({ type: 'time', nullable: true }) Hora!: string | null;
  @Column({ type: 'varchar', length: 30, nullable: true }) Nome!: string | null;
  @Column({ type: 'int', nullable: true }) Form1!: number | null;
  @Column({ type: 'int', nullable: true }) Form2!: number | null;
  @Column({ type: 'int', nullable: true }) Prod_1!: number | null;
  @Column({ type: 'int', nullable: true }) Prod_2!: number | null;
  @Column({ type: 'int', nullable: true }) Prod_3!: number | null;
  @Column({ type: 'int', nullable: true }) Prod_4!: number | null;
  @Column({ type: 'int', nullable: true }) Prod_5!: number | null;
  @Column({ type: 'int', nullable: true }) Prod_6!: number | null;
  @Column({ type: 'int', nullable: true }) Prod_7!: number | null;
  @Column({ type: 'int', nullable: true }) Prod_8!: number | null;
  @Column({ type: 'int', nullable: true }) Prod_9!: number | null;
  @Column({ type: 'int', nullable: true }) Prod_10!: number | null;
  @Column({ type: 'int', nullable: true }) Prod_11!: number | null;
  @Column({ type: 'int', nullable: true }) Prod_12!: number | null;
  @Column({ type: 'int', nullable: true }) Prod_13!: number | null;
  @Column({ type: 'int', nullable: true }) Prod_14!: number | null;
  @Column({ type: 'int', nullable: true }) Prod_15!: number | null;
  @Column({ type: 'int', nullable: true }) Prod_16!: number | null;
  @Column({ type: 'int', nullable: true }) Prod_17!: number | null;
  @Column({ type: 'int', nullable: true }) Prod_18!: number | null;
  @Column({ type: 'int', nullable: true }) Prod_19!: number | null;
  @Column({ type: 'int', nullable: true }) Prod_20!: number | null;
  @Column({ type: 'int', nullable: true }) Prod_21!: number | null;
  @Column({ type: 'int', nullable: true }) Prod_22!: number | null;
  @Column({ type: 'int', nullable: true }) Prod_23!: number | null;
  @Column({ type: 'int', nullable: true }) Prod_24!: number | null;
  @Column({ type: 'int', nullable: true }) Prod_25!: number | null;
  @Column({ type: 'int', nullable: true }) Prod_26!: number | null;
  @Column({ type: 'int', nullable: true }) Prod_27!: number | null;
  @Column({ type: 'int', nullable: true }) Prod_28!: number | null;
  @Column({ type: 'int', nullable: true }) Prod_29!: number | null;
  @Column({ type: 'int', nullable: true }) Prod_30!: number | null;
  @Column({ type: 'int', nullable: true }) Prod_31!: number | null;
  @Column({ type: 'int', nullable: true }) Prod_32!: number | null;
  @Column({ type: 'int', nullable: true }) Prod_33!: number | null;
  @Column({ type: 'int', nullable: true }) Prod_34!: number | null;
  @Column({ type: 'int', nullable: true }) Prod_35!: number | null;
  @Column({ type: 'int', nullable: true }) Prod_36!: number | null;
  @Column({ type: 'int', nullable: true }) Prod_37!: number | null;
  @Column({ type: 'int', nullable: true }) Prod_38!: number | null;
  @Column({ type: 'int', nullable: true }) Prod_39!: number | null;
  @Column({ type: 'int', nullable: true }) Prod_40!: number | null;
  
  // Unidades dos produtos
  @Column({ type: 'varchar', length: 2, nullable: true }) Unidade_1!: string | null;
  @Column({ type: 'varchar', length: 2, nullable: true }) Unidade_2!: string | null;
  @Column({ type: 'varchar', length: 2, nullable: true }) Unidade_3!: string | null;
  @Column({ type: 'varchar', length: 2, nullable: true }) Unidade_4!: string | null;
  @Column({ type: 'varchar', length: 2, nullable: true }) Unidade_5!: string | null;
  @Column({ type: 'varchar', length: 2, nullable: true }) Unidade_6!: string | null;
  @Column({ type: 'varchar', length: 2, nullable: true }) Unidade_7!: string | null;
  @Column({ type: 'varchar', length: 2, nullable: true }) Unidade_8!: string | null;
  @Column({ type: 'varchar', length: 2, nullable: true }) Unidade_9!: string | null;
  @Column({ type: 'varchar', length: 2, nullable: true }) Unidade_10!: string | null;
  @Column({ type: 'varchar', length: 2, nullable: true }) Unidade_11!: string | null;
  @Column({ type: 'varchar', length: 2, nullable: true }) Unidade_12!: string | null;
  @Column({ type: 'varchar', length: 2, nullable: true }) Unidade_13!: string | null;
  @Column({ type: 'varchar', length: 2, nullable: true }) Unidade_14!: string | null;
  @Column({ type: 'varchar', length: 2, nullable: true }) Unidade_15!: string | null;
  @Column({ type: 'varchar', length: 2, nullable: true }) Unidade_16!: string | null;
  @Column({ type: 'varchar', length: 2, nullable: true }) Unidade_17!: string | null;
  @Column({ type: 'varchar', length: 2, nullable: true }) Unidade_18!: string | null;
  @Column({ type: 'varchar', length: 2, nullable: true }) Unidade_19!: string | null;
  @Column({ type: 'varchar', length: 2, nullable: true }) Unidade_20!: string | null;
  @Column({ type: 'varchar', length: 2, nullable: true }) Unidade_21!: string | null;
  @Column({ type: 'varchar', length: 2, nullable: true }) Unidade_22!: string | null;
  @Column({ type: 'varchar', length: 2, nullable: true }) Unidade_23!: string | null;
  @Column({ type: 'varchar', length: 2, nullable: true }) Unidade_24!: string | null;
  @Column({ type: 'varchar', length: 2, nullable: true }) Unidade_25!: string | null;
  @Column({ type: 'varchar', length: 2, nullable: true }) Unidade_26!: string | null;
  @Column({ type: 'varchar', length: 2, nullable: true }) Unidade_27!: string | null;
  @Column({ type: 'varchar', length: 2, nullable: true }) Unidade_28!: string | null;
  @Column({ type: 'varchar', length: 2, nullable: true }) Unidade_29!: string | null;
  @Column({ type: 'varchar', length: 2, nullable: true }) Unidade_30!: string | null;
  @Column({ type: 'varchar', length: 2, nullable: true }) Unidade_31!: string | null;
  @Column({ type: 'varchar', length: 2, nullable: true }) Unidade_32!: string | null;
  @Column({ type: 'varchar', length: 2, nullable: true }) Unidade_33!: string | null;
  @Column({ type: 'varchar', length: 2, nullable: true }) Unidade_34!: string | null;
  @Column({ type: 'varchar', length: 2, nullable: true }) Unidade_35!: string | null;
  @Column({ type: 'varchar', length: 2, nullable: true }) Unidade_36!: string | null;
  @Column({ type: 'varchar', length: 2, nullable: true }) Unidade_37!: string | null;
  @Column({ type: 'varchar', length: 2, nullable: true }) Unidade_38!: string | null;
  @Column({ type: 'varchar', length: 2, nullable: true }) Unidade_39!: string | null;
  @Column({ type: 'varchar', length: 2, nullable: true }) Unidade_40!: string | null;
  
  @Column({ type: 'varchar', length: 255, nullable: true }) processedFile!: string | null;
  @Column({ type: 'varchar', length: 50, nullable: true }) Area!: string | null;
  @Column({ type: 'varchar', length: 100, nullable: true }) AreaDescricao!: string | null;
  
  // Propriedade para indexação dinâmica
  [key: string]: any;
}
